/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_white_imagesobelfilter_nativeSobelFilter */

#ifndef _Included_com_white_imagesobelfilter_nativeSobelFilter
#define _Included_com_white_imagesobelfilter_nativeSobelFilter
#ifdef __cplusplus
extern "C" {
#endif
#undef com_white_imagesobelfilter_nativeSobelFilter_MIN_PRIORITY
#define com_white_imagesobelfilter_nativeSobelFilter_MIN_PRIORITY 1L
#undef com_white_imagesobelfilter_nativeSobelFilter_NORM_PRIORITY
#define com_white_imagesobelfilter_nativeSobelFilter_NORM_PRIORITY 5L
#undef com_white_imagesobelfilter_nativeSobelFilter_MAX_PRIORITY
#define com_white_imagesobelfilter_nativeSobelFilter_MAX_PRIORITY 10L

JNIEXPORT void JNICALL Java_com_white_imagesobelfilter_nativeSobelFilter_init
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_white_imagesobelfilter_nativeSobelFilter_getPlatformName
  (JNIEnv *, jobject);
JNIEXPORT jstring JNICALL Java_com_white_imagesobelfilter_nativeSobelFilter_getDeviceName
  (JNIEnv *, jobject);
/*
 * Class:     com_white_imagesobelfilter_nativeSobelFilter
 * Method:    sobelFilter
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_white_imagesobelfilter_nativeSobelFilter_sobelFilter
  (JNIEnv *, jobject, jstring,jstring);

#ifdef __cplusplus
}
#endif
#endif
